version = 0.1

[default.global.parameters]
stack_name = "FastApiTransactionsEmailGenerator"

[default.deploy]
[default.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"