AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack for Stori's Transactions Email Sender

Parameters:
  Project:
    Description: "Project name."
    Type: "String"
    Default: "stori-transactions-email-sender"
  Stage:
    Description: "Stage name, should be dev or prod."
    Type: "String"
    AllowedValues:
      - "dev"
      - "prod"
  BucketName:
    Description: "Bucket name to store files."
    Type: "String"
  SecretName:
    Description: "Enail sender servide secret name."
    Type: "String"

Globals:
  Function:
    Timeout: 180

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-${Stage}-api"
      MemorySize: 256
      CodeUri: .
      Handler: src.api.main.handler
      Runtime: python3.9
      Environment:
        Variables:
          BUCKET_NAME: !ref BucketName
          SECRET_NAME: !ref SecretName
          STAGE: !Ref Stage
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*'
        - S3FullAccessPolicy:
            BucketName: !Sub BucketName

  Api:
    Name: !Sub "${Project}-${Stage}-http-api"
    Type: AWS::Serverless::HttpApi
    SrageName: !Ref Stage

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'