AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack for Stori's Transactions Email Sender

Parameters:
  Project:
    Description: "Project name."
    Type: "String"
    Default: "stori-transactions-email-sender"
  Stage:
    Description: "Stage name, should be dev or prod."
    Type: "String"
    AllowedValues:
      - "dev"
      - "prod"
  BucketName:
    Description: "Bucket name to store files."
    Type: "String"
  SecretName:
    Description: "Enail sender servide secret name."
    Type: "String"
  AppRunnerConnectionArn:
    Description: "App runner connection Arn."
    Type: "String"

Globals:
  Function:
    Timeout: 30

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-${Stage}-api"
      MemorySize: 512
      CodeUri: .
      Handler: src.api.main.handler
      Runtime: python3.12
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          SECRET_NAME: !Ref SecretName
          STAGE: !Ref Stage
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Policies:
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:stori*'
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      VpcConfig:
        SecurityGroupIds:
          - sg-0caac4ee042ea071e
          - sg-06773d9f2a2418747
        SubnetIds:
          - subnet-0eba33baff274049b
          - subnet-00326eed251a41661
          - subnet-0d6d5af9444661658
          - subnet-0d1cd1f453b97c1dd

  Api:
    Name: !Sub "${Project}-${Stage}-http-api"
    Type: AWS::Serverless::HttpApi
    SrageName: !Ref Stage


  AppRunnerVPCConnector:
    Type: AWS::AppRunner::VpcConnector
    Properties:
      SecurityGroups: 
        - sg-0caac4ee042ea071e
        - sg-06773d9f2a2418747
      Subnets: 
        - subnet-0eba33baff274049b
        - subnet-00326eed251a41661
        - subnet-0d6d5af9444661658
        - subnet-0d1cd1f453b97c1dd
      VpcConnectorName: !Sub "${Project}-${Stage}"


  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub "stori-api-app-runner"
      NetworkConfiguration:
        EgressConfiguration: 
          EgressType: VPC
          VpcConnectorArn: !Ref AppRunnerVPCConnector
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref AppRunnerConnectionArn
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: "https://github.com/montoyaobeso/transactions-email-generator"
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref Stage
          CodeConfiguration:
            ConfigurationSource: API
            CodeConfigurationValues:
              Runtime: PYTHON_3
              RuntimeEnvironmentVariables:
                -
                  Name: BUCKET_NAME
                  Value: !Ref BucketName
                -
                  Name: SECRET_NAME
                  Value: !Ref SecretName
                -
                  Name: STAGE
                  Value: !Ref Stage
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'