FROM python:3.12

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

COPY .env /code

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src /code/src

ENV POSTGRES_HOST=host.docker.internal

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "80"]